### ISSUE TITLE
Analyze .do files in Restud packages

### ISSUE THREAD

**Issue by korenmiklos** [codedthinking/Kezdi.jl#12]
- frequency distribution of commands
- usage of globals, locals
- usage of by, if, in
- usage of lead/lag operators and factor operators 
- usage of r() e() and s()

**Comment by gergelyattilakiss** [comment]
Sure, I think end of March is managable.

**Comment by korenmiklos** [comment]
Parsing do files should not be difficult. With the exception of some prefixes like by ... : or quietly, the first word is the command. 

Ok maybe comment parsing is also necessary. There four different ways to comment, *, /* */, // and ///

**Comment by gergelyattilakiss** [comment]
this and #14 should be done in https://github.com/REStud/github-data

**Comment by korenmiklos** [comment]
Indeed, this is duplicate of that
