### ISSUE TITLE
feat: display command

### ISSUE THREAD

**Issue by korenmiklos** [codedthinking/Kezdi.jl#147]
upon command generation, display what the user wrote 

useful for logging

**Comment by korenmiklos** [comment]
- https://github.com/JuliaDocs/IOCapture.jl

**Comment by jmboehm** [comment]
[macroexpand](https://docs.julialang.org/en/v1/base/base/#Base.macroexpand) might be useful for this (if I correctly interpret the issue).

**Comment by korenmiklos** [comment]
We want to mimic Stata logging experience: command and its output reported one after the other. 

I think we have enough info in StructuredCommand to recreate the original command the user wrote. 

Not yet sure, how to implement logging, though.
