### ISSUE TITLE
bug: introduce temporary variables in `@replace`

### ISSUE THREAD

**Issue by korenmiklos** [codedthinking/Kezdi.jl#175]
```julia
Multiple definitions for eltype_RHS and eltype_LHS

Combine all definitions into a single reactive cell using a `begin ... end` block.
```

This seems to be an issue of macro hygene.

**Comment by korenmiklos** [comment]
The issue arose in a Pluto notebook, where cells are not necessarily evaluated in order.

**Comment by gergelyattilakiss** [comment]
In the demo durint KTI @korenmiklos mentioned that this might be related to Pluto not recognizing changes in global variables.
