### ISSUE TITLE
debug compatibility with Julia 1.11

### ISSUE THREAD

**Issue by korenmiklos** [codedthinking/Kezdi.jl#195]

**Comment by korenmiklos** [comment]
@gergelyattilakiss with the current compat settings, it is only compatible with 1.11. I have 1.10 and tried to `update Kezdi`, I only got 0.5.2.

**Comment by gergelyattilakiss** [comment]
`1.10` works for me now, I could update to `0.5.4`. tried to solve `1.9` too but there are some julia limitations on the dependencies. However, using `develop` updates with `1.9` too and it does have the `reshape long` command.

**Comment by gergelyattilakiss** [comment]
Now works with `1.9` too, I close the issue.

**Comment by psungho** [comment]
does not work w/ 1.11.2
