### ISSUE TITLE
parse `by(variable1 variable2)`

### ISSUE THREAD

**Issue by korenmiklos** [codedthinking/Kezdi.jl#49]

**Comment by gergelyattilakiss** [comment]
@korenmiklos Is this fine with using `by(variable1,variable2)` or we specifically want the Stata like syntax?

**Comment by gergelyattilakiss** [comment]
Stata like syntax is gives parse error.

**Comment by korenmiklos** [comment]
`by(x, y)` is fine. Please write tests for it.
