### ISSUE TITLE
Bug: With.jl not installed properly as a dependency

### ISSUE THREAD

**Issue by gergelyattilakiss** [codedthinking/Kezdi.jl#62]
Fresh installs do not find our dependency of With.jl

**Comment by korenmiklos** [comment]
```
(@v1.10) pkg> add https://github.com/codedthinking/Kezdi.jl.git
     Cloning git-repo `https://github.com/codedthinking/Kezdi.jl.git`
    Updating git-repo `https://github.com/codedthinking/Kezdi.jl.git`
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package With [acd23e61]:
 With [acd23e61] log:
 ├─With [acd23e61] has no known versions!
 └─restricted to versions * by Kezdi [48308a23] — no versions left
   └─Kezdi [48308a23] log:
     ├─possible versions are: 0.3.0 or uninstalled
     └─Kezdi [48308a23] is fixed to version 0.3.0
```

**Comment by gergelyattilakiss** [comment]
https://juliacommunity.github.io/zulip-archive/stream/274208-helpdesk-(published)/topic/Package.20has.20no.20known.20versions!.20when.20using.20Pkg.2Edevelop.html

This was the only reliable source facing similar problem, the solution __IS__ to install separately With.jl, or include it in the package or publish it. 

So this should be a decision call, I am pro including With instead of publishing it. But than it will look weird to have to completely different things in the package so, we could include an install file in the repo that describes things? 

Then again the issue is that the authors we are shooting are not necessarily ready to take the burden for the tool to not just install from Julia but clone from github and then run a script... Let's talk about this sometime.

**Comment by korenmiklos** [comment]
Fine to have different modules in one package.
