### ISSUE TITLE
Bug: `@drop df a @if b<7` 

### ISSUE THREAD

**Issue by gergelyattilakiss** [codedthinking/Kezdi.jl#70]
This specific command is not wokring, either errors or if `bitmask` is removed gives back the `drop @if b<7` result.
![image](https://github.com/codedthinking/Kezdi.jl/assets/47605029/df955b6a-1ee4-41b6-8869-cd239a3848eb)

**Comment by korenmiklos** [comment]
`@drop a if @b < 7` should not work
