### ISSUE TITLE
Unable to load dta with df = use("temp/data.dta") or, equivalently, df = @use "temp/data.dta"

### ISSUE THREAD

**Issue by korenmiklos** [codedthinking/Kezdi.jl#88]

**Comment by korenmiklos** [comment]
@andrasvereckei can you copy more of the code and the error message?

**Comment by korenmiklos** [comment]
May be related to #73

**Comment by andrasvereckei** [comment]
> @andrasvereckei can you copy more of the code and the error message?

I think this issue is solved. 
Read balance panel with both methods on the server.
